[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the backend when in development
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Explicitly handle identity endpoint
[[redirects]]
  from = "/.netlify/identity"
  to = "/.netlify/identity"
  status = 200
  force = true

# Enable Netlify Identity
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173